services:
  api-gateway:
    runbooks:
      - name: "High Latency Runbook"
        url: "https://your-wiki.com/runbooks/high-latency"
    dashboards:
      - name: "API Gateway Dashboard"
        url: "https://your-grafana.com/d/api-gateway"